//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horoscope.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PredictionWeather {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PredictionWeather() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Horoscope.Properties.PredictionWeather", typeof(PredictionWeather).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Солнечно.
        /// </summary>
        internal static string weather1 {
            get {
                return ResourceManager.GetString("weather1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снег.
        /// </summary>
        internal static string weather10 {
            get {
                return ResourceManager.GetString("weather10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пасмурно.
        /// </summary>
        internal static string weather11 {
            get {
                return ResourceManager.GetString("weather11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Град.
        /// </summary>
        internal static string weather12 {
            get {
                return ResourceManager.GetString("weather12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Небольшой дождь.
        /// </summary>
        internal static string weather13 {
            get {
                return ResourceManager.GetString("weather13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переменная облачность.
        /// </summary>
        internal static string weather14 {
            get {
                return ResourceManager.GetString("weather14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Малооблачно.
        /// </summary>
        internal static string weather15 {
            get {
                return ResourceManager.GetString("weather15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шторм!.
        /// </summary>
        internal static string weather16 {
            get {
                return ResourceManager.GetString("weather16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экстремальный шторм!.
        /// </summary>
        internal static string weather17 {
            get {
                return ResourceManager.GetString("weather17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слабая буря!.
        /// </summary>
        internal static string weather18 {
            get {
                return ResourceManager.GetString("weather18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Умеренная буря!.
        /// </summary>
        internal static string weather19 {
            get {
                return ResourceManager.GetString("weather19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Облачно.
        /// </summary>
        internal static string weather2 {
            get {
                return ResourceManager.GetString("weather2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сильная буря!.
        /// </summary>
        internal static string weather20 {
            get {
                return ResourceManager.GetString("weather20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидаются осадки.
        /// </summary>
        internal static string weather3 {
            get {
                return ResourceManager.GetString("weather3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преимущественно облачно.
        /// </summary>
        internal static string weather4 {
            get {
                return ResourceManager.GetString("weather4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без осадков.
        /// </summary>
        internal static string weather5 {
            get {
                return ResourceManager.GetString("weather5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается ливень.
        /// </summary>
        internal static string weather6 {
            get {
                return ResourceManager.GetString("weather6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преимущественно облачно.
        /// </summary>
        internal static string weather7 {
            get {
                return ResourceManager.GetString("weather7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Облачно без осадков.
        /// </summary>
        internal static string weather8 {
            get {
                return ResourceManager.GetString("weather8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мокрый снег.
        /// </summary>
        internal static string weather9 {
            get {
                return ResourceManager.GetString("weather9", resourceCulture);
            }
        }
    }
}
